// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xtkprdvzcftmfdbvsjcs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh0a3ByZHZ6Y2Z0bWZkYnZzamNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3OTY4MjcsImV4cCI6MjA2NjM3MjgyN30.NgNaRwvKTr9M7Dxo_6P8pBcv0ywCXox16QOEHIVE6gk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
    // Sessione persistente per 7 giorni
    storage: typeof window !== 'undefined' ? window.localStorage : undefined,
    storageKey: 'cutburn-supabase-auth-token',
    flowType: 'pkce'
  },
  global: {
    headers: {
      'x-client-info': 'cutburn-app/1.0.0',
    },
  },
  // Configurazioni per sessioni lunghe
  db: {
    schema: 'public'
  },
  realtime: {
    params: {
      eventsPerSecond: 2
    }
  }
});